modLoader="javafml"
loaderVersion="[47,)"
license="GNU AGPLv3"

[[mods]]
modId="edivadlib"
version="${mod_version}"
displayName="EdivadLib"
updateJSONURL = "https://api.modrinth.com/updates/edivadlib/forge_updates.json"
issueTrackerURL="https://github.com/Edivad99/EdivadLib/issues"
modUrl="https://www.curseforge.com/minecraft/mc-mods/edivadlib"
authors="Edivad99"
description="Just a common library for all my mods"

[[dependencies.edivadlib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.edivadlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
