modLoader="javafml"
loaderVersion="[45,)"
license="GNU AGPLv3"

[[mods]]
modId="edivadlib"
version="${file.jarVersion}"
displayName="EdivadLib"
updateJSONURL="https://raw.githubusercontent.com/Edivad99/mod-version-controll/master/edivadlib_update.json"
issueTrackerURL="https://github.com/Edivad99/EdivadLib/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/edivadlib"
authors="edivad"
description="Just a common library for all my mods"

[[dependencies.edivadlib]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.edivadlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
