modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GNU AGPLv3"
issueTrackerURL = "https://github.com/Edivad99/EdivadLib/issues"

[[mods]]
  modId = "edivadlib"
  version = "${mod_version}"
  displayName = "EdivadLib"
  updateJSONURL = "https://api.modrinth.com/updates/edivadlib/forge_updates.json?neoforge=include"
  modUrl = "https://www.curseforge.com/minecraft/mc-mods/edivadlib"
  authors = "Edivad99"
  description = "Just a common library for all my mods"

[[dependencies.edivadlib]]
  modId = "neoforge"
  type = "required"
  versionRange = "${neo_version_range}"
  ordering = "NONE"
  side = "BOTH"
[[dependencies.edivadlib]]
  modId = "minecraft"
  type = "required"
  versionRange = "${minecraft_version_range}"
  ordering = "NONE"
  side = "BOTH"
